#include <gtest/gtest.h>

#include <cstdint>
#include <string>
#include <vector>

#include "Xtc/XtcParser.h"
#include "Xtc/XtcTypes.h"

// XTC/XTCH files come straight off the SD card (or a WebDAV upload) and are fully
// untrusted: a lying header must never cause an out-of-bounds read, an unbounded
// allocation, or a crash. Fixtures are generated by scripts/generate_test_xtc.py
// (deterministic; regenerate with `python3 scripts/generate_test_xtc.py`).
//
// Fixture layout (minimal.xtc): 56-byte header, 128-byte title + 64-byte author
// metadata, 16-byte page table entries at offset 248, then per-page 22-byte
// XTG/XTH header + bitmap. Pages are 16x4: 8 bitmap bytes for 1-bit XTG,
// 16 bytes (two bit planes) for 2-bit XTH.

static_assert(sizeof(xtc::XtcHeader) == 56, "XtcHeader must match the on-disk 56-byte layout");
static_assert(sizeof(xtc::PageTableEntry) == 16, "PageTableEntry must match the on-disk 16-byte layout");
static_assert(sizeof(xtc::XtgPageHeader) == 22, "XtgPageHeader must match the on-disk 22-byte layout");

namespace {

std::string fixture(const char* name) { return std::string(XTC_FIXTURE_DIR "/") + name; }

std::vector<uint8_t> expectedBitmap(uint8_t seed, size_t size) {
  std::vector<uint8_t> data(size);
  for (size_t i = 0; i < size; ++i) data[i] = static_cast<uint8_t>(seed + i);
  return data;
}

}  // namespace

TEST(XtcParser, ParsesHeaderAndMetadataOfMinimalFile) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);
  EXPECT_TRUE(parser.isOpen());
  EXPECT_EQ(parser.getPageCount(), 2u);
  EXPECT_EQ(parser.getBitDepth(), 1u);
  EXPECT_EQ(parser.getWidth(), 16u);
  EXPECT_EQ(parser.getHeight(), 4u);
  EXPECT_EQ(parser.getTitle(), "Minimal Test Book");
  EXPECT_EQ(parser.getAuthor(), "CrossPoint QA");
  EXPECT_FALSE(parser.hasChapters());
}

TEST(XtcParser, ResolvesPageTableEntriesAtDocumentedOffsets) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);

  // Independently computed layout: table at 56 + 128 + 64 = 248, two 16-byte
  // entries, so page 0 data starts at 280 and page 1 at 280 + (22 + 8) = 310.
  xtc::PageInfo info{};
  ASSERT_TRUE(parser.getPageInfo(0, info));
  EXPECT_EQ(info.offset, 280u);
  EXPECT_EQ(info.size, 30u);
  EXPECT_EQ(info.width, 16u);
  EXPECT_EQ(info.height, 4u);
  EXPECT_EQ(info.bitDepth, 1u);

  ASSERT_TRUE(parser.getPageInfo(1, info));
  EXPECT_EQ(info.offset, 310u);
  EXPECT_EQ(info.size, 30u);
}

TEST(XtcParser, LoadsDistinctBitmapDataPerPage) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);

  uint8_t buffer[64] = {0};
  ASSERT_EQ(parser.loadPage(0, buffer, sizeof(buffer)), 8u);
  EXPECT_EQ(std::vector<uint8_t>(buffer, buffer + 8), expectedBitmap(0xA0, 8));

  ASSERT_EQ(parser.loadPage(1, buffer, sizeof(buffer)), 8u);
  EXPECT_EQ(std::vector<uint8_t>(buffer, buffer + 8), expectedBitmap(0xB0, 8));
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::OK);
}

TEST(XtcParser, XtchVariantUsesTwoBitPlanes) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtch").c_str()), xtc::XtcError::OK);
  EXPECT_EQ(parser.getBitDepth(), 2u);
  EXPECT_EQ(parser.getPageCount(), 2u);

  // 16x4 pixels at 2bpp: ((16*4 + 7) / 8) * 2 = 16 bytes.
  uint8_t buffer[64] = {0};
  ASSERT_EQ(parser.loadPage(0, buffer, sizeof(buffer)), 16u);
  EXPECT_EQ(std::vector<uint8_t>(buffer, buffer + 16), expectedBitmap(0xC0, 16));
}

TEST(XtcParser, StreamingLoadDeliversSameBytesInOrder) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);

  std::vector<uint8_t> assembled;
  size_t expectedOffset = 0;
  const xtc::XtcError err = parser.loadPageStreaming(
      1,
      [&](const uint8_t* data, size_t size, size_t offset) {
        EXPECT_EQ(offset, expectedOffset);
        assembled.insert(assembled.end(), data, data + size);
        expectedOffset += size;
      },
      3 /* deliberately tiny chunk size */);

  EXPECT_EQ(err, xtc::XtcError::OK);
  EXPECT_EQ(assembled, expectedBitmap(0xB0, 8));
}

TEST(XtcParser, RejectsPageIndexOutOfRange) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);

  xtc::PageInfo info{};
  EXPECT_FALSE(parser.getPageInfo(2, info));

  uint8_t buffer[64];
  EXPECT_EQ(parser.loadPage(2, buffer, sizeof(buffer)), 0u);
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::PAGE_OUT_OF_RANGE);
  EXPECT_EQ(parser.loadPageStreaming(2, [](const uint8_t*, size_t, size_t) {}), xtc::XtcError::PAGE_OUT_OF_RANGE);
}

TEST(XtcParser, LoadPageWithoutOpenFailsCleanly) {
  xtc::XtcParser parser;
  uint8_t buffer[8];
  EXPECT_EQ(parser.loadPage(0, buffer, sizeof(buffer)), 0u);
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::FILE_NOT_FOUND);
}

TEST(XtcParser, MissingFileReportsFileNotFound) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("does_not_exist.xtc").c_str()), xtc::XtcError::FILE_NOT_FOUND);
  EXPECT_FALSE(parser.isOpen());
}

TEST(XtcParser, EmptyFileReportsReadError) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("empty.xtc").c_str()), xtc::XtcError::READ_ERROR);
  EXPECT_FALSE(parser.isOpen());
}

TEST(XtcParser, TruncatedHeaderReportsReadError) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("truncated_header.xtc").c_str()), xtc::XtcError::READ_ERROR);
  EXPECT_FALSE(parser.isOpen());
}

TEST(XtcParser, NonXtcContentReportsInvalidMagic) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("bad_magic.xtc").c_str()), xtc::XtcError::INVALID_MAGIC);
  EXPECT_FALSE(xtc::XtcParser::isValidXtcFile(fixture("bad_magic.xtc").c_str()));
  EXPECT_TRUE(xtc::XtcParser::isValidXtcFile(fixture("minimal.xtc").c_str()));
  EXPECT_TRUE(xtc::XtcParser::isValidXtcFile(fixture("minimal.xtch").c_str()));
}

TEST(XtcParser, UnsupportedVersionIsRejected) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("bad_version.xtc").c_str()), xtc::XtcError::INVALID_VERSION);
}

TEST(XtcParser, ZeroPageCountIsRejectedAsCorrupted) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("zero_pages.xtc").c_str()), xtc::XtcError::CORRUPTED_HEADER);
}

TEST(XtcParser, PageCountExceedingFileSizeIsRejected) {
  // Header claims 500 pages; the 340-byte file cannot hold a 8000-byte page table.
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("page_count_lie.xtc").c_str()), xtc::XtcError::CORRUPTED_HEADER);
}

TEST(XtcParser, PageCountJustPastTableBoundsIsRejected) {
  // 6 claimed pages need a 96-byte table: it fits inside the 340-byte file but
  // not between the table offset (248) and EOF, so the offset-aware bounds
  // check must still reject it.
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("page_count_lie_subtle.xtc").c_str()), xtc::XtcError::CORRUPTED_HEADER);
}

TEST(XtcParser, AbsurdPageCountIsRejectedWithoutAllocation) {
  // pageCount = 0xFFFF (the field is uint16_t, so this is the largest possible
  // lie) claims a ~1MB page table. The parser reads page table entries one at a
  // time and must reject the bounds up front rather than trusting the count.
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("absurd_page_count.xtc").c_str()), xtc::XtcError::CORRUPTED_HEADER);
  EXPECT_FALSE(parser.isOpen());
}

TEST(XtcParser, ZeroPageTableOffsetIsRejected) {
  xtc::XtcParser parser;
  EXPECT_EQ(parser.open(fixture("zero_table_offset.xtc").c_str()), xtc::XtcError::CORRUPTED_HEADER);
}

TEST(XtcParser, PageOffsetPastEofFailsAtLoadWithoutCrash) {
  // Documents current behavior: open() validates the page table bounds but not
  // each entry's data offset, so the lie is only caught when the page is read.
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("offset_past_eof.xtc").c_str()), xtc::XtcError::OK);

  uint8_t buffer[64];
  EXPECT_EQ(parser.loadPage(0, buffer, sizeof(buffer)), 0u);
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::READ_ERROR);
  EXPECT_EQ(parser.loadPageStreaming(0, [](const uint8_t*, size_t, size_t) {}), xtc::XtcError::READ_ERROR);
}

TEST(XtcParser, OverlappingPageRangesAreToleratedToday) {
  // Both table entries point at page 0's data. The parser performs no overlap
  // validation; this test documents the current lenient behavior (both reads
  // succeed and return the same bytes) so any tightening shows up here.
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("overlap_pages.xtc").c_str()), xtc::XtcError::OK);

  uint8_t first[64] = {0};
  uint8_t second[64] = {0};
  ASSERT_EQ(parser.loadPage(0, first, sizeof(first)), 8u);
  ASSERT_EQ(parser.loadPage(1, second, sizeof(second)), 8u);
  EXPECT_EQ(std::vector<uint8_t>(first, first + 8), std::vector<uint8_t>(second, second + 8));
  EXPECT_EQ(std::vector<uint8_t>(first, first + 8), expectedBitmap(0xA0, 8));
}

TEST(XtcParser, LyingPageDimensionsCannotOverrunCallerBuffer) {
  // The page header claims 480x800 (48000 bitmap bytes) but the file holds 8.
  // A too-small caller buffer must be refused outright; a large buffer must
  // surface the short read as an error instead of returning fabricated data.
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("page_dims_lie.xtc").c_str()), xtc::XtcError::OK);

  uint8_t small[64];
  EXPECT_EQ(parser.loadPage(0, small, sizeof(small)), 0u);
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::MEMORY_ERROR);

  std::vector<uint8_t> large(48000, 0xEE);
  EXPECT_EQ(parser.loadPage(0, large.data(), large.size()), 0u);
  EXPECT_EQ(parser.getLastError(), xtc::XtcError::READ_ERROR);
}

TEST(XtcParser, ChapterRangesAreClampedAndInvalidOnesDropped) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("chapters.xtc").c_str()), xtc::XtcError::OK);
  ASSERT_TRUE(parser.hasChapters());

  // Fixture stores three 1-based chapter records over a 4-page book:
  //   "Intro" (1..2), "Overflow End" (4..999), "Past The End" (200..210).
  const auto& chapters = parser.getChapters();
  ASSERT_EQ(chapters.size(), 2u);

  EXPECT_EQ(chapters[0].name, "Intro");
  EXPECT_EQ(chapters[0].startPage, 0u);  // converted to 0-based
  EXPECT_EQ(chapters[0].endPage, 1u);

  EXPECT_EQ(chapters[1].name, "Overflow End");
  EXPECT_EQ(chapters[1].startPage, 3u);
  EXPECT_EQ(chapters[1].endPage, 3u);  // clamped to last page
}

TEST(XtcParser, ChapterOffsetReadIgnoresHeaderPaddingBytes) {
  // chapters_padded.xtc is chapters.xtc with 0xDEADBEEF in the header's 4-byte
  // padding field (0x34). chapterOffset is a uint32_t at 0x30 (XtcTypes.h); a
  // parser that reads it as a uint64_t folds the padding into the offset's high
  // half, fails the bounds checks, and silently drops every chapter.
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("chapters_padded.xtc").c_str()), xtc::XtcError::OK);
  ASSERT_TRUE(parser.hasChapters());

  const auto& chapters = parser.getChapters();
  ASSERT_EQ(chapters.size(), 2u);
  EXPECT_EQ(chapters[0].name, "Intro");
  EXPECT_EQ(chapters[0].startPage, 0u);
  EXPECT_EQ(chapters[0].endPage, 1u);
  EXPECT_EQ(chapters[1].name, "Overflow End");
}

TEST(XtcParser, CloseResetsStateAndAllowsReuse) {
  xtc::XtcParser parser;
  ASSERT_EQ(parser.open(fixture("chapters.xtc").c_str()), xtc::XtcError::OK);
  parser.close();
  EXPECT_FALSE(parser.isOpen());
  EXPECT_EQ(parser.getPageCount(), 0u);
  EXPECT_TRUE(parser.getTitle().empty());

  ASSERT_EQ(parser.open(fixture("minimal.xtc").c_str()), xtc::XtcError::OK);
  EXPECT_EQ(parser.getPageCount(), 2u);
}
